spring:

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:library

  h2:
    console:
      enabled: true

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library
