spring:

  batch:
    job:
      enabled: false

  datasource:
    url: jdbc:h2:mem:library

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library
