version: '3.3'
services:
  db:
    image: mongo
    volumes:
      - db_volume:/data/db

  backend:
    build:
      ./backend
    ports:
    - 8080:8080
    depends_on:
      - db

  frontend:
    build:
      ./frontend
    ports:
    - 80:80
    depends_on:
      - backend

volumes:
  db_volume:
