spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library
  datasource:
    url: jdbc:h2:mem:library
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
