spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  instance:
    instance-id: "${spring.application.name}:${server.port}"
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  prefix: /api
  routes:
    book-registry: /book/**

server:
  port: 8765
