DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    TITLE    VARCHAR(255) UNIQUE,
    GENRE_ID INT NOT NULL,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID)
);

DROP TABLE IF EXISTS BOOKS_AUTHORS;
CREATE TABLE BOOKS_AUTHORS
(
    BOOK_ID   INT,
    AUTHOR_ID INT,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID)
);
